config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :membership_requests, only: %i[index create update]
  end
  resources :issues do
    resources :comments, only: %i[create destroy]
  end
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'static_pages#home'
end

app/models/project_membership_request.rb
class ProjectMembershipRequest < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :user, uniqueness: { scope: :project }

  def self.find_by_user_and_project(user, project)
    return nil unless user && project
    ProjectMembershipRequest.find_by(user: user, project: project)
  end
end

app/controllers/project_membership_requests_controller.rb
class ProjectMembershipRequestsController < ApplicationController
  before_action :authenticate_user!, :project
  before_action :verify_request_is_for_self, only: [:create]
  before_action :verify_project_admin, only: [:index, :destroy]

  def index
    @requests = ProjectMembershipRequest.where(project: @project)
  end

  def create
    @membership_request = ProjectMembershipRequest.new(membership_request_params)
    if @membership_request.save
      flash[:success] = "Your request to join #{@project.name} has been sent."
      redirect_to @project
    else
      flash[:danger] = "Your request to join the project couldn't be sent."
      redirect_to projects_path
    end
  end

  def destroy
    @request = ProjectMembershipRequest.find_by(id: membership_request_params[:id],
                                                project_id: membership_request_params[:project_id])
    if @request&.destroy
      flash[:success] = "Membership request was denied."
    else
      flash[:success] = "Membership request was accepted."
    end

    redirect_to project_project_membership_requests_path
  end

  private

  def verify_request_is_for_self
    unless current_user&.id == params[:user_id]&.to_i
      flash[:danger] = "You can only make project membership requests for yourself."
      redirect_to projects_path
    end
  end
  
  def verify_project_admin
    unless current_user&.is_admin_for?(project: @project)
      flash[:danger] = "You can't view membership requests unless you are a project admin."
      redirect_to @project
    end
  end

  def project
    @project = Project.find_by(id: params[:project_id])
  end

  def membership_request_params
    puts "PARAMS======================= #{params}"
    params.permit(:id, :user_id, :project_id)
  end
end

app/views/project_membership_requests/index.html.erb
<br />
<h1>Membership requests for <%= @project.name %></h1>

<% if @requests.any? %>
  <% @requests.each do |request| %>
    <div class='row my-3'>
      <div class='card border-dark col-9 mx-auto'>
        <div class='card-body'>
          <h5 class="card-title">New membership request</h5>
          <p class="card-text">User <%= request.user.email %> has requested to join your project.</p>
          <%= link_to 'Accept request', '#', class: 'btn btn-primary' %>
          <%= link_to 'Deny request', project_project_membership_request_path(project_id: request.project_id, id: request.id), method: :delete, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>There aren't any requests to join your project right now.</p>
<% end %>

<%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>