config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :membership_requests, only: %i[index create update]
  end
  resources :issues do
    resources :comments, only: %i[create destroy]
  end
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'static_pages#home'
end

app/models/issue.rb
class Issue < ApplicationRecord
  PRIORITIES = %w[critical major normal minor].freeze
  CATEGORIES = %w[requirements design development bugfix testing documentation].freeze
  STATES = ['open', 'in progress', 'ready for review', 'under review', 'reviewed - see comments', 'complete',
            'duplicate', 'obsolete', "won't fix"].freeze

  validates :title,
            presence: true,
            allow_blank: false,
            length: { minimum: 5,
                      maximum: 50 }
  validates :priority,
            inclusion: { in: PRIORITIES },
            allow_blank: true

  validates :category,
            inclusion: { in: CATEGORIES },
            allow_blank: true

  validates :state,
            inclusion: { in: STATES },
            allow_blank: true

  belongs_to :project
  has_many :comments, dependent: :destroy
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :issue, only: %i[show edit update destroy].freeze
  before_action :verify_project_membership, only: %i[create new edit update destroy].freeze

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      flash[:success] = "Issue \"#{@issue.title}\" successfully created."
      redirect_to @issue
    else
      flash[:danger] = 'Issue could not be created.'
      render 'new'
    end
  end

  def new
    @project = Project.find(params[:project_id])
  end

  def show
    @comments = @issue.comments
  end

  def edit
  end

  def update
    if @issue.update(issue_params)
      flash[:success] = "Issue \"#{@issue.title}\" updated"
      redirect_to @issue
    else
      flash[:danger] = 'Issue could not be updated.'
      render 'edit'
    end
  end

  def destroy
    success_redirect = @issue.project
    if @issue.destroy
      flash[:success] = "Issue \"#{@issue.title}\" deleted."
      redirect_to success_redirect
    else
      flash[:danger] = "Issue \"#{@issue.title}\" could not be deleted."
      redirect_to 'edit'
    end
  end

  private

  def verify_project_membership
    project = @issue&.project || Project.find_by(id: params[:project_id]) || Project.find_by(id: params[:issue][:project_id])

    unless authenticate_user! && current_user.is_member_of?(project: project)
      flash[:danger] = 'You must be a member of the project to do that.'
      redirect_to project
    end
  end

  def issue
    @issue = Issue.find_by(id: params[:id])
    render_404 unless @issue
  end

  def issue_params
    params.require(:issue).permit(:title, :description, :project_id, :priority, :category, :state)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/edit.html.erb
<% provide(:title, "Edit Issue") %>

<h1>Edit "<%= @issue.title %>"</h1>

<%= form_with(model: @issue, local: true) do |f| %>
  <%= f.label :title %>
  <br />
  <%= f.text_field :title %><br />
  <br />
  <br />

  <%= f.label :description %>
  <br />
  <%= f.text_area :description, cols: 60, rows: 10 %><br />
  <br />
  <br />

  <%= f.label :category %>
  <br />
  <%= f.select :category, %w[requirements design development bugfix testing documentation] %>
  <br />
  <br />

  <%= f.label :priority %>
  <br />
  <%= f.select :priority, ['critical', 'major', 'normal', 'minor'] %>
  <br />
  <br />

  <%= f.label :state %>
  <br />
  <%= f.select :state, ['open', 'in progress', 'ready for review', 'under review', 'reviewed - see comments', 'complete',
                        'duplicate', 'obsolete', "won't fix"] %>
  <br />
  <br />

  <%= f.label :project_id %>
  <br />
  <%= f.number_field :project_id, readonly: true %>
  <br />
  <br />

  <%= f.submit 'Save changes', class: 'btn btn-primary' %>
  <%= link_to 'Delete Issue', issue_path, method: :delete, data: { confirm: 'Are you sure you want to delete this issue? This action cannot be undone.' }, class: 'btn btn-danger' %>
  <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
<% end %>

app/views/issues/new.html.erb
<% provide(:title, 'New Issue') %>
<h1>New Issue for "<%= @project.name %>"</h1>

<%= form_with(model: @issue, scope: :issue, url: '/issues', method: 'post', local: true) do |f| %>
  <%= f.label :title %>
  <br />
  <%= f.text_field :title %>
  <br />
  <br />

  <%= f.label :description %>
  <br />
  <%= f.text_area :description %>
  <br />
  <br />

  <%= f.label :category %>
  <br />
  <%= f.select :category, %w[requirements design development bugfix testing documentation] %>
  <br />
  <br />

  <%= f.label :priority %>
  <br />
  <%= f.select :priority, %w[minor normal major critical] %>
  <br />
  <br />

  <%= f.label :state %>
  <br />
  <%= f.select :state, ['open', 'in progress', 'ready for review', 'under review', 'reviewed - see comments', 'complete',
                        'duplicate', 'obsolete', "won't fix"] %>
  <br />
  <br />

  <%= f.label :project_id %>
  <br />
  <%= f.number_field :project_id, value: @project.id, readonly: true %>
  <br />
  <br />

  <%= f.submit 'Create Issue', class: 'btn btn-primary' %>
  <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
<% end %>

app/views/issues/show.html.erb
<br />
<div class="row">
  <div class="col"><h1><%= @issue.title %></h1></div>
</div>
<div class="row">
  <div class="col-9">
    <p><%= @issue.description %></p>
  </div>
  <div class="col-3">
    <div class="card float-right">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><b>Project:</b> <%= link_to @issue.project.name, @issue.project %></li>
        <li class="list-group-item"><b>State:</b> <%= @issue.state&.titleize %></li>
        <li class="list-group-item"><b>Priority:</b> <%= @issue.priority&.titleize %></li>
        <li class="list-group-item"><b>Category:</b> <%= @issue.category&.titleize %></li>
        <li class="list-group-item"><b>Created:</b> <%= @issue.created_at.strftime('%F') %></li>
      </ul>
    </div>
  </div>
</div>
<% if current_user&.is_member_of?(project: @issue.project) %>
  <%= link_to 'Edit Issue', edit_issue_path(@issue), class: 'btn btn-primary' %>
  <%= link_to 'Delete Issue', @issue, method: :delete, class: 'btn btn-danger' %>
  <br />
  <br />
  <br />
  <small>Commenting as <%= current_user.email %></small>
  <%= form_for :comment, url: issue_comments_path(issue_id: @issue.id), method: :post, local: true do |f| %>
    <%= f.text_area :content, placeholder: 'Add a comment here...', cols: 60, rows: 5 %>
    <%= f.hidden_field :issue_id, value: @issue.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <br />
    <%= f.submit 'Add comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>

<br />
<br />
<h3 class='mt-3'>Comments</h3>
<% if @comments.any? %>
  <% @comments.each do |comment| %>
    <div class='card mb-3 pl-3 pt-3'>
      <div class='row'>
        <div class='col-sm-11'>
          <p><small><%= comment.user.email %> commented <%= comment.created_at.strftime('%m/%d/%Y %I:%M') %></small></p>
          <p><%= comment.content %></p>
        </div>
        <% if comment.user == current_user %>
          <%= link_to issue_comment_path(issue_id: @issue.id, id: comment.id), method: :delete, data: { confirm: 'Are you sure you want to remove your comment?' } do %>
            <div class='col-sm-1' style='position: absolute; right: 0;'>
              <button type='button' class='close' aria-label='Close'>
                <span aria-hidden='true'>&times;</span>
              </button>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <p>No one has commented on this issue yet.</p>
<% end %>
<br />
<br />
<br />