config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :membership_requests, only: %i[index create update]
  end
  resources :issues do
    resources :comments, only: %i[create destroy]
  end
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'static_pages#home'
end

app/models/membership_request.rb
class MembershipRequest < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/membership_requests_controller.rb
class MembershipRequestsController < ApplicationController
  before_action :authenticate_user!, :project
  before_action :verify_request_is_for_self, only: [:create]
  before_action :verify_project_admin, only: [:index, :update]

  def index
    @requests = @project.open_membership_requests
  end

  def create
    @membership_request = MembershipRequest.new(user_id: params[:user_id],
                                                project_id: params[:project_id])
    if @membership_request.save
      flash[:success] = "Your request to join #{@project.name} has been sent."
      redirect_to @project
    else
      flash[:danger] = "Your request to join the project couldn't be sent."
      redirect_to projects_path
    end
  end

  def update
    @request = MembershipRequest.find_by(id: params[:request_id])
    request_handler = MembershipRequestHandler.new(@request)

    if params[:admin_action] == 'accept'
      request_handler.accept
    else
      request_handler.reject
    end

    redirect_to projects_path
  end

  private

  def verify_request_is_for_self
    unless current_user&.id == params[:user_id]&.to_i
      flash[:danger] = "You can only make project membership requests for yourself."
      redirect_to projects_path
    end
  end
  
  def verify_project_admin
    unless current_user&.is_admin_for?(project: @project)
      flash[:danger] = "You can't view membership requests unless you are a project admin."
      redirect_to @project
    end
  end

  def project
    @project = Project.find_by(id: params[:project_id])
  end
end

app/helpers/membership_requests_helper.rb
module MembershipRequestsHelper
end

app/views/membership_requests/index.html.erb
<br />
<h1>Membership requests for <%= @project.name %></h1>

<% if @requests.any? %>
  <% @requests.each do |request| %>
    <div class='row my-3'>
      <div class='card border-dark col-9 mx-auto'>
        <div class='card-body'>
          <h5 class="card-title">New membership request</h5>
          <p class="card-text">User <%= request.user.email %> has requested to join your project.</p>
          <div class='row'>
            <%= form_with url: project_membership_request_path(id: @project.id), method: :put, local: true do |f| %>
              <%= f.hidden_field :request_id, value: request.id, type: "hidden" %>
              <%= f.hidden_field :admin_action, value: 'accept', type: "hidden" %>
              <%= f.submit 'Accept request', class: 'btn btn-primary mr-2' %>
            <% end %>
            <%= form_with url: project_membership_request_path(id: @project.id), method: :put, local: true do |f| %>
              <%= f.hidden_field :request_id, value: request.id, type: "hidden" %>
              <%= f.hidden_field :admin_action, value: 'reject', type: "hidden" %>
              <%= f.submit 'Reject request', class: 'btn btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>There aren't any requests to join your project right now.</p>
<% end %>

<%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>