config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :membership_requests, only: %i[index create update]
  end
  resources :issues do
    resources :comments, only: %i[create destroy]
  end
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'static_pages#home'
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name,
            presence: true,
            uniqueness: true,
            allow_blank: false,
            length: { minimum: 3, maximum: 30 }

  has_many :issues, dependent: :destroy
  has_many :project_roles, dependent: :destroy
  has_many :membership_requests, dependent: :destroy

  def open_membership_requests
    membership_requests.where(
      accepted_at: nil,
      rejected_at: nil
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :verify_project_admin, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      ProjectRole.create(user: current_user, project: @project, role: 'admin')
      flash[:success] = "Project \"#{@project.name}\" successfully created."
      redirect_to @project
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:success] = "Project \"#{@project.name}\" updated."
      redirect_to @project
    else
      flash[:danger] = "Project could not be updated."
      render 'edit'
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = "Project \"#{@project.name}\" deleted."
      redirect_to projects_path
    else
      redirect_to @project
    end
  end

  private

  def verify_project_admin
    unless current_user&.is_admin_for?(project: @project)
      flash[:danger] = 'You must be an admin of the project to do that.'
      redirect_to @project
    end
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def project
    @project = Project.find_by(id: params[:id])
    render_404 unless @project
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.erb
<% provide(:title, "Edit Project") %>

<h1>Edit "<%= @project.name %>"</h1>

<%= form_with(model: @project, local: true) do |f| %>
  <%= f.label :name %>
  <br />
  <%= f.text_field :name %><br />
  <br />

  <%= f.label :description %>
  <br />
  <%= f.text_area :description %><br />
  <br />

  <%= f.submit 'Save changes', class: 'btn btn-primary' %>
  <%= link_to 'Delete Project', project_path, method: :delete, data: { confirm: 'Are you sure you want to delete this project? This action cannot be undone.' }, class: 'btn btn-danger' %>
<% end %>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<br />
<h1>Projects Directory</h1>

<% if user_signed_in? %>
  <div>
    <h3>Your Projects</h3>
    <% if current_user.projects.any? %>
      <% current_user.projects.each do |project| %>
        <p><%= link_to project.name, project %></p>
      <% end %>
    <% else %>
      <p>You haven't joined any projects yet.</p>
    <% end %>
  </div>
<% else %>
  <div>
    <h3>Your Projects</h3>
    <p><%= link_to 'Log in', new_user_session_path %> to view your projects.</p>
  </div>
<% end %>

<br />
<hr />
<br />

<div>
  <h3>All Projects</h3>
  <% @projects.each do |project| %>
    <p><%= link_to project.name, project %></p>
  <% end %>
  <%= link_to 'Create Project', { :action => 'new' }, method: :get, class: 'btn btn-primary' %>
</div>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h1>New Project</h1>

<%= form_with(model: @project, local: true) do |f| %>
  <%= f.label :name %>
  <br />
  <%= f.text_field :name %>
  <br />
  <br />

  <%= f.label :description %>
  <br />
  <%= f.text_area :description %>
  <br />
  <br />

  <%= f.submit 'Create Project', class: 'btn btn-primary' %>
  <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
<% end %>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>
<br />
<h1><%= @project.name %>
  <% if current_user&.is_admin_for?(project: @project) %>
    <%= link_to '<i class="fas fa-cog fa-xs"></i>'.html_safe, edit_project_path %>
  <% end %>
</h1>

<div class='row'>
  <p>
    <%= @project.description %>
    <br />
    <br />
    <% if current_user&.is_admin_for?(project: @project) && @project.open_membership_requests.any? %>
      <%= link_to 'View membership requests', project_membership_requests_path(@project), class: 'btn btn-primary' %>
    <% end %>
  </p>
</div>
<br />
<div class='row'>
  <p>
    <h3>Project Issues</h3>
    <table class='table table-hover'>
      <thead>
        <tr>
          <th scope='col'>ID</th>
          <th scope='col'>Priority</th>
          <th scope='col'>Category</th>
          <th scope='col'>State</th>
          <th scope='col'>Title</th>
          <th scope='col'>Description</th>
          <th scope='col'>Created</th>
        </tr>
      </thead>
      <tbody>
        <% @project.issues.each do |issue| %>
          <tr>
            <th scope='row'><%= link_to issue.id, issue %></th>
            <td><%= issue.priority&.capitalize %></td>
            <td><%= issue.category&.capitalize %></td>
            <td><%= issue.state&.titleize %></td>
            <td><%= link_to issue.title, issue %></td>
            <td><%= issue.description.truncate(30)%></td>
            <td><%= issue.created_at.strftime('%F') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class='row'>
      <% if current_user&.is_member_of?(project: @project) %>
        <%= link_to 'New Issue', new_issue_path(project_id: @project.id), class: 'btn btn-primary' %>
      <% elsif current_user&.can_request_membership_for?(project: @project) %>
        <%= link_to 'Request to join project', project_membership_requests_path(user_id: current_user.id, project_id: @project.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </p>
</div>